import { sectionCopy } from './sections'

export const GITHUB_URL = 'https://github.com/miguelbonifaz/react-toast-notifications'

export const copy = {
    en: {
        nav: {
            demo: 'Demo',
            guide: 'How it works',
            github: 'GitHub',
        },
        hero: {
            eyebrow: 'React toast notifications',
            title: 'Feedback, without the friction.',
            body: 'A small, accessible toast layer for the moments when your interface needs to speak up.',
            demo: 'Try the playground',
            github: 'View on GitHub',
            visualLabel: 'Live package preview',
            visualFile: 'toast-demo.jsx',
            visualLine: 'Your UI just got a little clearer.',
        },
        demo: {
            eyebrow: 'Live playground',
            title: 'Trigger the states. Feel the difference.',
            body: 'Every control below calls the real package API. Stack a few messages, keep one around, or move the viewport.',
            trigger: 'Trigger a toast',
            stack: 'Stack three',
            dismiss: 'Dismiss all',
            custom: 'Custom icon',
            persistent: 'Keep it open',
            position: 'Viewport position',
            workspace: 'Calendar workspace',
            today: 'Tuesday, April 16',
            schedule: 'Today’s schedule',
            open: 'Open',
            ready: 'Ready for feedback',
            status: 'Live package output',
            typeLabels: {
                created: 'Created',
                updated: 'Updated',
                cancelled: 'Cancelled',
                success: 'Success',
                info: 'Info',
                warning: 'Warning',
                error: 'Error',
            },
            positions: {
                'top-left': 'Top left',
                'top-center': 'Top center',
                'top-right': 'Top right',
                'bottom-left': 'Bottom left',
                'bottom-center': 'Bottom center',
                'bottom-right': 'Bottom right',
            },
        },
        messages: {
            created: 'Appointment created successfully.',
            updated: 'Your appointment was updated.',
            cancelled: 'The appointment was cancelled.',
            success: 'Changes saved successfully.',
            info: 'A new update is available.',
            warning: 'This notification stays until dismissed.',
            error: 'Something needs your attention.',
            custom: 'Custom icon, same simple API.',
            ready: 'Toast queue ready. Try a control below.',
        },
        ...sectionCopy.en,
    },
    es: {
        nav: {
            demo: 'Demo',
            guide: 'Cómo funciona',
            github: 'GitHub',
        },
        hero: {
            eyebrow: 'Notificaciones toast para React',
            title: 'Feedback, sin fricción.',
            body: 'Una capa toast pequeña y accesible para los momentos en que tu interfaz necesita hacerse escuchar.',
            demo: 'Probar el playground',
            github: 'Ver en GitHub',
            visualLabel: 'Vista previa del paquete',
            visualFile: 'toast-demo.jsx',
            visualLine: 'Tu interfaz acaba de ser más clara.',
        },
        demo: {
            eyebrow: 'Playground en vivo',
            title: 'Activa los estados. Siente la diferencia.',
            body: 'Cada control llama a la API real del paquete. Apila mensajes, deja uno abierto o mueve el viewport.',
            trigger: 'Activar un toast',
            stack: 'Apilar tres',
            dismiss: 'Cerrar todos',
            custom: 'Icono personalizado',
            persistent: 'Dejar abierto',
            position: 'Posición del viewport',
            workspace: 'Espacio de calendario',
            today: 'Martes, 16 de abril',
            schedule: 'Agenda de hoy',
            open: 'Abierto',
            ready: 'Listo para feedback',
            status: 'Salida real del paquete',
            typeLabels: {
                created: 'Creado',
                updated: 'Actualizado',
                cancelled: 'Cancelado',
                success: 'Éxito',
                info: 'Info',
                warning: 'Advertencia',
                error: 'Error',
            },
            positions: {
                'top-left': 'Arriba izquierda',
                'top-center': 'Arriba centro',
                'top-right': 'Arriba derecha',
                'bottom-left': 'Abajo izquierda',
                'bottom-center': 'Abajo centro',
                'bottom-right': 'Abajo derecha',
            },
        },
        messages: {
            created: 'La cita fue creada correctamente.',
            updated: 'La cita fue actualizada.',
            cancelled: 'La cita fue cancelada.',
            success: 'Los cambios se guardaron correctamente.',
            info: 'Hay una nueva actualización disponible.',
            warning: 'Esta notificación queda abierta hasta cerrarla.',
            error: 'Algo necesita tu atención.',
            custom: 'Icono personalizado, misma API simple.',
            ready: 'Cola de toasts lista. Prueba un control.',
        },
        ...sectionCopy.es,
    },
}

export const toastTypes = ['created', 'updated', 'cancelled', 'success', 'info', 'warning', 'error']

export const positionTypes = [
    'top-left',
    'top-center',
    'top-right',
    'bottom-left',
    'bottom-center',
    'bottom-right',
]
