export const GITHUB_URL = 'https://github.com/miguelbonifaz/react-toast-notifications'

export const copy = {
    en: {
        nav: {
            github: 'GitHub',
        },
        hero: {
            eyebrow: 'React toast notifications',
            title: 'Subtle design, natural interaction.',
            body: 'An accessible and extensible toast notification layer for React, with precise motion and a simple integration.',
            github: 'View on GitHub',
            playground: {
                launch: 'Launch notification',
                messages: [
                    'Saved before you could blink.',
                    'Look at you, getting things done.',
                    'Miracles do happen.',
                    'Nobody panic — it worked.',
                    'Even the code is impressed.',
                    'Nailed it. Probably.',
                    'Success has entered the chat.',
                    'Nice work — everything is ready.',
                    'Success looks good on you.',
                    'Done before anyone noticed.',
                    'That was suspiciously easy.',
                    'You clicked a button. Heroic.',
                    'The toast has spoken.',
                    'Done and dusted.',
                    'That worked perfectly.',
                    'Mission accomplished.',
                    'Your notification has arrived.',
                    'Consider it done.',
                    'The technology cooperated for once.',
                    'No magic required. Almost.',
                ],
                positions: {
                    'bottom-center': 'Bottom center',
                    'bottom-left': 'Bottom left',
                    'bottom-right': 'Bottom right',
                    'top-center': 'Top center',
                    'top-left': 'Top left',
                    'top-right': 'Top right',
                },
                position: 'Position',
                type: 'Type',
                duration: 'duration in seconds',
                types: {
                    error: 'Error',
                    info: 'Info',
                    success: 'Success',
                    warning: 'Warning',
                },
            },
        },
    },
    es: {
        nav: {
            github: 'GitHub',
        },
        hero: {
            eyebrow: 'Notificaciones toast para React',
            title: 'Diseño sutil, interacción natural.',
            body: 'Una capa toast con estética cuidada, movimiento preciso y una integración simple para React.',
            github: 'Ver en GitHub',
            playground: {
                launch: 'Lanzar notificación',
                messages: [
                    'Guardado antes de que pudieras parpadear.',
                    'Mira nada más, haciendo cosas.',
                    'Los milagros sí existen.',
                    'Que nadie entre en pánico: funcionó.',
                    'Hasta el código está impresionado.',
                    'Lo clavaste. Probablemente.',
                    'El éxito acaba de entrar al chat.',
                    'Buen trabajo: todo está listo.',
                    'El éxito te queda bien.',
                    'Listo antes de que alguien lo notara.',
                    'Eso fue sospechosamente fácil.',
                    'Hiciste clic en un botón. Heroico.',
                    'El toast ha hablado.',
                    'Listo y sin polvo.',
                    'Eso funcionó perfectamente.',
                    'Misión cumplida.',
                    'Tu notificación ha llegado.',
                    'Considéralo hecho.',
                    'La tecnología cooperó por una vez.',
                    'No hizo falta magia. Casi.',
                ],
                positions: {
                    'bottom-center': 'Abajo centro',
                    'bottom-left': 'Abajo izquierda',
                    'bottom-right': 'Abajo derecha',
                    'top-center': 'Arriba centro',
                    'top-left': 'Arriba izquierda',
                    'top-right': 'Arriba derecha',
                },
                position: 'Posición',
                type: 'Tipo',
                duration: 'Duración (segundos)',
                types: {
                    error: 'Error',
                    info: 'Información',
                    success: 'Éxito',
                    warning: 'Advertencia',
                },
            },
        },
    },
}
